
export const GET_TOP_ARTICLES = 'GET_TOP_ARTICLES';
export const GET_MORE_ARTICLES = 'GET_MORE_ARTICLES';
export const GET_ARTICLES_DETAILS = 'GET_ARTICLES_DETAILS';
export const TOP_ARTICLES_ERROR = 'TOP_ARTICLES_ERROR';
export const GET_SEARCH_ARTICLES= 'GET_SEARCH_ARTICLES';
export const RESET_ARTICLES= ' RESET_ARTICLES';


